spartamarket/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path('profile/<str:username>/', views.profile, name="profile"),
    path('<int:user_id>/follow/', views.follow, name="follow"),
]

spartamarket/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path("", views.products, name="products"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/like", views.like, name="like"),
    path("<int:pk>/update", views.update, name="update"),
    path("<int:pk>/delete", views.delete, name="delete"),
]

spartamarket/spartamarket/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('products/', include("products.urls")),
]

spartamarket/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    created_at = models.DateTimeField(auto_now_add=True)
    following = models.ManyToManyField(
        "self", related_name="followers", symmetrical=False
        )
    

spartamarket/products/models.py
from django.db import models
from django.conf import settings


class Products(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

    author = models.ForeignKey( #유저테이블이랑 포린키로 이미 엮여있다! ;;;
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="product"
    )

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_products"
    )
    def __str__(self):
        return self.title

spartamarket/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()

spartamarket/products/forms.py
from django import forms
from .models import Products

class ProductsForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = "__all__" #모든 필드를 다 불러올 거야/만들거야 
        exclude = ("creat_at", "author", "like_users")
        # exclude = ("creat_at", "update_at", "author", "like_users") #얘네 제외하고!

spartamarket/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from .models import User
from products.models import Products

def login(request):
    form = AuthenticationForm(data=request.POST)
    if form.is_valid():
        auth_login(request, form.get_user())
        return redirect("products:products")
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("products:products")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("products:products")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)


def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username) #유저 테이블 안에 있는 유저, 이미 프로덕트가 들어가 있다 ;;;;
    context = {
        "member": member,
        }
    return render(request, 'accounts/profile.html', context)


def follow(request, user_id):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_id)
        if member != request.user:
            if member.followers.filter(pk=request.user.pk).exists():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect("accounts:profile", username = member.username)
    else:
        return redirect('accounts:login')

spartamarket/products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Products
from .forms import ProductsForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
# Create your views here.


def products(request):
    products = Products.objects.all().order_by("-id")
    context = { "products" : products }
    return render(request, "products/products.html", context)

@login_required
def create(request):
    if request.method == "POST":
        form = ProductsForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.author =  request.user
            product.save()
            return redirect('products:detail', product.pk)
    else:
        form = ProductsForm()

    context = { "form" : form }
    return render(request, 'products/create.html', context)

def detail(request, pk):
    products = get_object_or_404(Products,pk = pk)
    context = { "products" : products }
    return render(request, "products/detail.html", context)

def like(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Products,pk=pk)
        if product.like_users.filter(pk=request.user.pk).exists():
            product.like_users.remove(request.user)
        else:
            product.like_users.add(request.user)
        return redirect("products:products")
    return redirect("accounts:login")

@login_required
def update(request, pk):
    product = get_object_or_404(Products, pk=pk)
    if request.method == "POST":
        form = ProductsForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save()
            return redirect('products:detail', product.pk)
    else:
        form = ProductsForm(instance=product)
    
    context = { 
        "form" : form ,
        "product" : product
        }
    return render(request, 'products/update.html', context)

def delete(request, pk):
    if request.user.is_authenticated:
        product = get_object_or_404(Products, pk=pk)
        product.delete()
        return redirect('products:products')
    return redirect('products:detail', pk)

spartamarket/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1>로그인 페이지 입니다</h1>

<form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit">로그인</button>
</form>
{% endblock content %}

spartamarket/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<h1>{{ member.username }}님의 프로필</h1>
<h3>가입일:{{ member.created_at}}</h3>
<h3>팔로워 수: {{ member.followers.count }}</h3>
<h3>팔로우 수: {{ member.following.count }}</h3>

{% if request.user != member %}
    <form action="{% url "accounts:follow" member.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in member.followers.all %}
            <input type="submit" value="언팔로우">
        {% else %}
            <input type="submit" value="팔로우">
        {% endif %}
    </form>
{% endif %}

<h3>등록한 물품</h3> 
{% for product in member.product.all %}
    <a href="{% url "products:detail" product.pk %}"> {{ product.title }} </a>
    <br>
    <hr>
{% endfor %}

<h3>내가 좋아요한 물건</h3> 
{% for product in member.like_products.all %}
    <a href="{% url "products:detail" product.pk %}"> {{ product.title }} </a>
    <br>
    <hr>
{% endfor %}


{% endblock content %}

spartamarket/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입 페이지입니다</h1>
<form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">회원가입</button>
</form>
{% endblock content %}

spartamarket/products/templates/products/create.html
{% extends "base.html" %}

{% block content %}

<h1>물건을 등록해봅시다!</h1>

<form action="{% url "products:create" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">저장</button>
</form>

<a href="{% url "products:products" %}">물건들 보러가기</a>
{% endblock content %}

spartamarket/products/templates/products/detail.html
{% extends "base.html" %}

{% block content %}

<h1>상세페이지</h1>
<p>제목:{{ products.title }}</p>
<a href="{% url "accounts:profile" products.author.username %}">
    <p>작성자: {{ products.author.username }}</p>
</a>
<p>내용:{{ products.content }}</p>
{% if user == products.author %}

<a href="{% url "products:update" products.pk %}">
    <button>수정하기</button>
</a>

<form action="{% url "products:delete" products.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
</form>

{% endif %}

<a href="{% url "products:products" %}">물건들 보러가기</a>

{% endblock content %}

spartamarket/products/templates/products/products.html
{% extends "base.html" %}

{% block content %}

<h1>뚱이의 SPARTA MARKET</h1>

{% if request.user.is_authenticated %}
    <a href="{% url 'products:create' %}">
        <button>등록하기</button>
    </a>
{% else %}
    <a href="{% url 'accounts:login' %}">
        <button>로그인 하고 등록하기</button>
    </a>
{% endif %}

{% for product in products %}
    <a href="{% url "products:detail" product.pk %}">
        <p>[{{ product.id }}]{{ product.title }}</p>
    </a>

    <form action="{% url "products:like" product.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in product.like_users.all %}
            <input type="submit" value="좋아요 취소">
        {% else %}
            <input type="submit" value="좋아요">
        {% endif %}
    </form>


    {% endfor %}

{% endblock content %}

spartamarket/products/templates/products/update.html
{% extends "base.html" %}

{% block content %}

<h1>수정 페이지</h1>
<form action="{% url "products:update" product.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">수정</button>
</form>

<a href="{% url 'products:detail' product.pk %}">이전으로</a>
{% endblock content %}

spartamarket/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    body{
        background-image:url("https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2F1xuG8%2FbtsGMHE4aYm%2FTEtlD5tq411xWAVkZSc3Hk%2Fimg.jpg");
        background-repeat : no-repeat 
        width: cover;

    }
    </style>
</head>
<body>
    <div class="navar">
        {% if request.user.is_authenticated %}
        <form action="{% url "accounts:logout" %}" method="POST" >
            {% csrf_token %}
            <button type="submit">로그아웃</button>
        </form>        
        {% else %}
        <a href="{% url "accounts:login" %}">로그인</a>
        <a href="{% url "accounts:signup" %}">회원가입</a>
        {% endif %}
    </div>
    {% block content %}
    {% endblock content %}
</body>
</html>